port 1234
bind 0.0.0.0
protected-mode yes
allow-ip 10.0.0.0/32
tls-port 1235
tls-cert-file "tls/cert.pem"
tls-key-file "tls/key.pem"
dbfilename dump.rdb
appendonly yes
appendfilename appendonly.aof
appendfsync everysec
maxmemory 67108864
maxmemory-policy allkeys-lru
maxmemory-samples 10
save 3600 1
save 300 100
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 67108864
user alice on "$argon2id$v=19$m=19456,t=2,p=1$Je1D9YKZayQIFGMtrx1QtQ$V64ZkJqXLLijfPJpHMHquhhUwZaHTiD6StqU2NOwGto" ~* &news.* +@all
auditlog "/tmp/myred-audit.log"
