port 1234
requirepass s3cret
dbfilename dump.rdb
appendonly yes
appendfilename appendonly.aof
appendsync everysec
maxmemory 67108864
maxmemory-policy allkeys-lru
maxmemory-samples 10
save 3600 1
save 300 100
