port 1234
requirepass "#1ec1c26b50d5d3c58d9583181af8076655fe00756bf7285940ba3670f99fcba0"
dbfilename dump.rdb
appendonly yes
appendfilename appendonly.aof
appendfsync everysec
maxmemory 67108864
maxmemory-policy allkeys-lru
maxmemory-samples 10
save 3600 1
save 300 100
user carol on "$argon2id$v=19$m=19456,t=2,p=1$QRR2YXcOxJzXZKNAtSLVBw$MkQGXRWElaFiBuW2lcDhMMRqDWO0QJE+mfJhyUFmXZQ" ~* -@all +@read
user alice on "#6624974ea2baffac164422e4490376c1c31313cd97724ae8ce62fb3f0a0370f2" ~app:* -@all +@read
rename-command config __admin_config__
rename-command flushall ""
auditlog "/tmp/myred-audit.log"
