port 1338
protected-mode yes
bind 0.0.0.0
dbfilename dump.rdb
appendonly no
appendfilename appendonly.aof
appendfsync everysec
maxmemory 0
maxmemory-policy noeviction
maxmemory-samples 10
notify-keyspace-events ""
save 3600 1
save 300 100
save 60 10000
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 67108864
repl-backlog-size 1048576
replicaof 127.0.0.1 1336
